bug_flask/flaskweb/app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

class User(UserMixin, db.Model):
	__tablename__ = 'User'
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(64), unique=True)
	password_hash = db.Column(db.String(128))
	role = db.Column(db.Boolean, default=False)
	location = db.Column(db.String(64))
	about_me = db.Column(db.Text())

	posts = db.relationship('Post', backref='author', lazy='dynamic')
	plans = db.relationship('Plan', backref='author', lazy='dynamic')

	def is_administrator(self):
		return self.role

	@property
	def password(self):
		raise AttributeError('password is not readable attribute')

	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	def __repr__(self):
		return '<User %r>' % self.username

class Post(db.Model):
	__tablename__ = 'Posts'
	id = db.Column(db.Integer, primary_key=True)
	bug_url = db.Column(db.Text)
	body = db.Column(db.Text)
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	flag = db.Column(db.Boolean, default=False)
	author_id = db.Column(db.Integer, db.ForeignKey('User.id'))

class Plan(db.Model):
	__tablename__ = 'Plans'
	id = db.Column(db.Integer, primary_key=True)
	content = db.Column(db.Text)
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	author_id = db.Column(db.Integer, db.ForeignKey('User.id'))


@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

bug_flask/flaskweb/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import Length, URL, DataRequired

class EditProfileForm(FlaskForm):
	location = StringField("Location", validators=[Length(0,60)])
	about_me = StringField("About me")
	submit = SubmitField("Submit")

class BugForm(FlaskForm):
	bug_url = StringField("bug's URL", validators=[URL(message='This Not a URL'),Length(0,2048)])
	body = TextAreaField("Please describe the problem in detail")
	submit = SubmitField("Submit")

class PlanForm(FlaskForm):
	content = TextAreaField("Write your plan")
	submit = SubmitField("Submit")

class ImportForm(FlaskForm):
	myplans = FileField("upload your plans", validators=[DataRequired()])
	submit = SubmitField("Import")

bug_flask/flaskweb/app/__init__.py
import os
from flask import Flask, redirect, url_for, session, render_template, flash
from flask_script import Manager
from flask_bootstrap import Bootstrap
from flask_moment  import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config
from werkzeug.routing import BaseConverter

class RegexConverter(BaseConverter):
    def __init__(self, url_map, *items):
        super(RegexConverter, self).__init__(url_map)
        self.regex = items[0]

manager = Manager()
bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = "auth.login"

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)
	
	app.url_map.converters['regex'] = RegexConverter
	bootstrap.init_app(app)
	moment.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)

	from . main import main as main_blueprint
	app.register_blueprint(main_blueprint)
	from . auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint, url_prefix='/auth')
	return app

bug_flask/flaskweb/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

bug_flask/flaskweb/app/main/views.py
from datetime import datetime
from flask import render_template, redirect, url_for, flash, abort, make_response, request, session
from flask_login import login_required, current_user
from . import main
from .. import db
from ..models import User, Post, Plan
from  .forms import EditProfileForm, BugForm, PlanForm, ImportForm
from .xmlparse import MyContentHandler
import xml.sax
import hashlib
import random

@main.route('/', methods=['GET', 'POST'], defaults={'path': ''})
@main.route('/<path:path>')
def index(path):
	return render_template('index.html')

@main.route('/user/<username>')
@login_required
def user(username):
	user = User.query.filter_by(username=username).first()
	if user is None:
		abort(404)
	return render_template('user.html', user=user)

@main.route('/<regex("edit(.*)"):url>/', methods=['GET', 'POST'])
@login_required
def edit(url):
	form = EditProfileForm()
	if form.validate_on_submit():
		current_user.location = form.location.data
		current_user.about_me = form.about_me.data
		db.session.add(current_user)
		flash('You Profile has been updated')
		return redirect(url_for('.user', username=current_user.username))
	form.location.data = current_user.location
	form.about_me.data = current_user.about_me
	return render_template('edit.html', form=form)


@main.route('/<regex("post_bug(.*)"):url>/', methods=['GET', 'POST'])
@login_required
def post_bug(url):
	form = BugForm()
	if form.validate_on_submit():
		post = Post(body=form.body.data, bug_url=form.bug_url.data, author=current_user._get_current_object())
		db.session.add(post)
		return redirect(url_for('.post_bug', url="post_bug"))
	posts = current_user.posts.order_by(Post.timestamp.desc()).all()
	return render_template('post.html', form=form, posts=posts)

@main.route('/<regex("write_plan(.*)"):url>/', methods=['GET', 'POST'])
@login_required
def write_plan(url):
	form = PlanForm()
	if form.validate_on_submit():
		plan = Plan(content=form.content.data, author=current_user._get_current_object())
		db.session.add(plan)
		return redirect(url_for('.write_plan', url="write_plan"))
	plans = current_user.plans.order_by(Plan.timestamp.desc()).all()
	return render_template('plan.html', form=form, plans=plans)

@main.route('/88e6955d09f5ab8e75a96706507b04a5', methods=['GET', 'POST'])
@login_required
def Check_the_message():
	if current_user.role == False:
		abort(404)
	posts = Post.query.filter_by(flag=False).order_by(Post.timestamp.asc()).limit(50)
	urls = []
	for post in posts:
		urls.append(post.bug_url)
		post.flag = True
		db.session.add(post)
	return render_template('/88e6955d09f5ab8e75a96706507b04a5.html', urls=urls)


@main.route('/<regex("export(.*)"):url>/', methods=['GET', 'POST'])
@login_required
def export(url):
	content = """<?xml version="1.0" encoding="UTF-8"?>\n<plans>\n"""
	plans = current_user.plans.order_by(Plan.timestamp.desc()).all()
	for plan in plans:
		content += "\t<plan>\n"
		content += "\t\t<content>" + plan.content +"</content>\n"
		content += "\t</plan>\n"
	content += "</plans>"
	response = make_response(content)
	response.headers["Content-Disposition"] = "attachment; filename=myplans.xml"
	return response

@main.route('/<regex("import_and_export(.*)"):url>/', methods=['GET', 'POST'])
@login_required
def import_and_export(url):
	form = ImportForm()
	if form.validate_on_submit():
		my_xml = request.files['myplans'].read()
		my_xml = str(my_xml, encoding = "utf-8")

		if 'http' in my_xml.lower():
			flash('Hacker, absolutely big hacker!!!')
			return redirect(url_for('.import_and_export', url="import_and_export"))

		if len(my_xml) > 1500:
			flash('别太长了，短期计划就好了~')
			return redirect(url_for('.import_and_export', url="import_and_export"))

		if my_xml.upper().count('ENTITY') > 1:
			flash('出题人表示很抱歉，最多只能一个ENTITY')
			return redirect(url_for('.import_and_export', url="import_and_export"))

		plansList = []

		try:
			parser = MyContentHandler(plansList)
			xml.sax.parseString(my_xml, parser)
		except Exception as e:
			return render_template('xml_error.html')

		for i in plansList:
			plan = Plan(content=i, author=current_user._get_current_object())
			db.session.add(plan)

		flash('Import success')
		return redirect(url_for('.write_plan', url="write_plan"))
	else:
		return render_template('import_and_export.html', form=form)

bug_flask/flaskweb/app/templates/88e6955d09f5ab8e75a96706507b04a5.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}post bug{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>See Message</h1>
</div>
<ul class="posts">
    {% for url in urls %}
    	<li class="post">
    		<div class="post-url">{{ url }}</div>
    	</li>
    {% endfor %}
</ul>
{% endblock %}

bug_flask/flaskweb/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Syc Work Notes</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
					<li><a href="{{ url_for('main.user', username=current_user.username) }}">UserInfo</a></li>
					<li><a href="{{ url_for('main.edit', url='edit') }}">EditMyinfo</a></li>
                    <li><a href="{{ url_for('main.write_plan', url='write_plan') }}">Write_your_plan</a></li>
                    <li><a href="{{ url_for('main.import_and_export', url='import_and_export') }}">import_and_export</a></li>
					<li><a href="{{ url_for('main.post_bug', url='post_bug') }}">Post Bug</a></li>
					<li><a href="{{ url_for('auth.logout', url='logout') }}">Sign Out</a></li>
				{% else %}
					<li><a href="{{ url_for('auth.login', url='login') }}">Sign In</a></li>
				{% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

bug_flask/flaskweb/app/templates/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

bug_flask/flaskweb/app/templates/import_and_export.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}import and export{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Import or Export your Plan</h1>
</div>
<input class="btn btn-default" id="submit" name="submit" type="button" value="Export" onclick="window.open('/export')">
{{ wtf.quick_form(form) }}
{% endblock %}

bug_flask/flaskweb/app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Index{% endblock %}

{% block page_content %}
<div class="page-header">
	{% if current_user.is_authenticated %}
		<h1>Hello, {{ current_user.username }}</h1>
		<p>This is an internal version of the Syc working notes project. You can write down your recent task memo. If you find bug, you are welcome to submit it to the administrator in time~</p>
		<p>	#BY a programmer who stayed up late at night#</p>
	{% else %}
    	<h1>Hello, Ctfer!</h1>
    {% endif %}
</div>
{% endblock %}

bug_flask/flaskweb/app/templates/plan.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}post bug{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Write down your secret plan. Rest assured that no one will see you.</h1>
</div>
<ul class="posts">
    {{ wtf.quick_form(form) }}
    {% for plan in plans %}
    	<li class="post">
    	   <div class="post-date">
    		  {{ moment(plan.timestamp).fromNow() }}
              {{ plan.content }}
    	   </div>
    	</li>
    {% endfor %}
</ul>
{% endblock %}

bug_flask/flaskweb/app/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}post bug{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Post Bug</h1>
</div>
<ul class="posts">
    {{ wtf.quick_form(form) }}
    {% for post in posts %}
    	<li class="post">
    	<div class="post-date">
    		{{ moment(post.timestamp).fromNow() }}
    		{% if post.flag %}
    		*Have been consulted*
    		{% else %}
    		#Not consulted#
    		{% endif %}
    	</div>
    		<div class="post-url">{{ post.bug_url }}</div>
    		<div class="post-body">{{ post.body }}</div>
    	</li>
    {% endfor %}
</ul>
{% endblock %}

bug_flask/flaskweb/app/templates/user.html
{% extends "base.html" %}

{% block title %}UserInfo{% endblock %}

{% block page_content %}
<div class="page-header">
	<h1>{{user.username}}</h1>
	{% if user.name or user.location %}
	<p>
		{% if user.name %}{{ user.name }}{% endif %}
		{% if user.location %}-{{ user.location }}{% endif %}
		{% if user.about_me %}{{ user.about_me }}{% endif %}
	</p>
	{% endif %}
</div>
{% endblock %}

bug_flask/flaskweb/app/templates/xml_error.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}xml error{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>XML import error, please check if the XML syntax is wrong</h1>
</div>
{% endblock %}